# -*- coding: utf-8 -*-
"""chatbot avukatlık.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15tnPC7Mz8AAEWtLMda44Afr-wFaZsjQz
"""

# 1. Kütüphaneleri Tertemiz Kur
!pip install -q -U google-generativeai PyPDF2 gradio Pillow

import google.generativeai as genai
import PyPDF2
import gradio as gr
from google.colab import userdata
from PIL import Image
import os

# 2. API VE AKILLI MODEL SEÇİMİ
try:
    api_key = userdata.get('GEMINI_API_KEY')
    genai.configure(api_key=api_key)

    # Erişilebilir modelleri bul ve en yenisini seç
    modeller = [m.name for m in genai.list_models() if 'generateContent' in m.supported_generation_methods]

    # Öncelik sırası: 1.5-flash (hızlı/görsel), değilse 1.5-pro, o da yoksa ilk bulunan
    if 'models/gemini-1.5-flash' in modeller:
        secilen_model = 'models/gemini-1.5-flash'
    elif 'models/gemini-pro' in modeller:
        secilen_model = 'models/gemini-pro'
    else:
        secilen_model = modeller[0]

    model = genai.GenerativeModel(secilen_model)
    print(f"✅ Bağlantı Başarılı! Kullanılan Model: {secilen_model}")
except Exception as e:
    print(f"❌ API Hatası: {e}")

# 3. VERİ SAKLAMA
hafiza = {"veri": None, "tur": None}

def dosya_isle(file):
    global hafiza
    if file is None: return "⚠️ Dosya bekleniyor..."

    uzanti = os.path.splitext(file.name)[1].lower()
    try:
        if uzanti == ".pdf":
            reader = PyPDF2.PdfReader(file.name)
            metin = " ".join([p.extract_text() or "" for p in reader.pages])
            hafiza["veri"] = metin[:20000]
            hafiza["tur"] = "pdf"
            return "✅ PDF Analiz Edildi. Sorunları yanıtlamaya hazırım."
        else:
            hafiza["veri"] = Image.open(file.name)
            hafiza["tur"] = "gorsel"
            return "✅ Görsel/Fotoğraf Algılandı. Belgeyi tartışabiliriz."
    except Exception as e:
        return f"❌ Okuma hatası: {e}"

def sohbet(mesaj, history):
    global hafiza
    if not hafiza["tur"]: return "Lütfen önce bir belge yükleyin."

    try:
        if hafiza["tur"] == "gorsel":
            # Görsel için multimodal istek
            res = model.generate_content([f"Hukuk asistanı olarak yanıtla: {mesaj}", hafiza["veri"]])
        else:
            # PDF metni için istek
            res = model.generate_content(f"Belge içeriği: {hafiza['veri']}\n\nSoru: {mesaj}")

        return res.text
    except Exception as e:
        return f"⚠️ API Yanıt Vermedi: {e}\n\nNot: API anahtarınızın günlük kotası dolmuş olabilir."

# 4. ARAYÜZ
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# ⚖️ AI Avukatlık Şirketi Asistanı")
    with gr.Row():
        yukle = gr.File(label="Dosya veya Görsel Atın")
        bilgi = gr.Textbox(label="Sistem Mesajı", interactive=False)

    yukle.change(dosya_isle, inputs=yukle, outputs=bilgi)
    gr.ChatInterface(fn=sohbet, title="Hukuki Analiz Paneli")

demo.launch(debug=True)

